Repository Tave100Shot/Server, pull requests merged in 2023-12, with the labels that each got.

#14 feat 요구하는 백준 문제에 대한 해답 블로그 전달
  build.gradle
  src/main/java/com/api/TaveShot/domain/search/controller/SearchController.java
  src/main/java/com/api/TaveShot/domain/search/dto/GoogleItemDto.java
  src/main/java/com/api/TaveShot/domain/search/dto/GoogleListResponseDto.java
  src/main/java/com/api/TaveShot/domain/search/dto/GoogleResponseDto.java
  src/main/java/com/api/TaveShot/domain/search/service/SearchService.java
  src/main/java/com/api/TaveShot/global/success/SuccessResponse.java
  src/main/java/com/api/TaveShot/global/success/SuccessResponseStatus.java
  src/main/java/com/api/TaveShot/global/success/SuccessStatus.java
Labels: :sparkles: Feature, 박정곤, :twisted_rightwards_arrows: PullRequest

#19 feat 유저 solvedac 와 GitHub 연동 및 인증
  build.gradle
  src/main/java/com/api/TaveShot/domain/Member/domain/Member.java
  src/main/java/com/api/TaveShot/domain/Member/domain/Tier.java
  src/main/java/com/api/TaveShot/domain/Member/editor/MemberEditor.java
  src/main/java/com/api/TaveShot/domain/authorization/controller/AuthorizationController.java
  src/main/java/com/api/TaveShot/domain/authorization/dto/GitHubRepositoryInfo.java
  src/main/java/com/api/TaveShot/domain/authorization/dto/MemberResponse.java
  src/main/java/com/api/TaveShot/domain/authorization/dto/SolvedUserInfo.java
  src/main/java/com/api/TaveShot/domain/authorization/service/AuthorizationService.java
  src/main/java/com/api/TaveShot/domain/authorization/service/GitHubApiService.java
  src/main/java/com/api/TaveShot/domain/authorization/service/SolvedAcApiService.java
  src/main/java/com/api/TaveShot/domain/comment/controller/CommentApiController.java
  src/main/java/com/api/TaveShot/domain/comment/converter/CommentConverter.java
  src/main/java/com/api/TaveShot/domain/comment/domain/Comment.java
  src/main/java/com/api/TaveShot/domain/comment/dto/request/CommentCreateRequest.java
  src/main/java/com/api/TaveShot/domain/comment/dto/request/CommentUpdateRequest.java
  src/main/java/com/api/TaveShot/domain/comment/dto/response/CommentResponse.java
  src/main/java/com/api/TaveShot/domain/comment/repository/CommentRepository.java
  src/main/java/com/api/TaveShot/domain/comment/service/CommentService.java
  src/main/java/com/api/TaveShot/domain/post/image/converter/ImageConverter.java
  src/main/java/com/api/TaveShot/domain/post/image/domain/Image.java
  src/main/java/com/api/TaveShot/domain/post/image/dto/ImageResponse.java
  src/main/java/com/api/TaveShot/domain/post/image/repository/ImageRepository.java
  src/main/java/com/api/TaveShot/domain/post/image/service/ImageService.java
  src/main/java/com/api/TaveShot/domain/post/post/controller/PostApiController.java
  src/main/java/com/api/TaveShot/domain/post/post/converter/PostConverter.java
  src/main/java/com/api/TaveShot/domain/post/post/domain/Post.java
  src/main/java/com/api/TaveShot/domain/post/post/domain/PostTier.java
  src/main/java/com/api/TaveShot/domain/post/post/dto/request/PostCreateRequest.java
  src/main/java/com/api/TaveShot/domain/post/post/dto/request/PostEditRequest.java
  src/main/java/com/api/TaveShot/domain/post/post/dto/request/PostSearchCondition.java
  src/main/java/com/api/TaveShot/domain/post/post/dto/response/PostListResponse.java
  src/main/java/com/api/TaveShot/domain/post/post/dto/response/PostResponse.java
  src/main/java/com/api/TaveShot/domain/post/post/editor/PostEditor.java
  src/main/java/com/api/TaveShot/domain/post/post/repository/PostRepository.java
  src/main/java/com/api/TaveShot/domain/post/post/repository/PostRepositoryCustom.java
  src/main/java/com/api/TaveShot/domain/post/post/repository/PostRepositoryImpl.java
  src/main/java/com/api/TaveShot/domain/post/post/service/PostService.java
  src/main/java/com/api/TaveShot/global/config/RedisConfig.java
  src/main/java/com/api/TaveShot/global/config/S3ClientConfig.java
  src/main/java/com/api/TaveShot/global/config/S3FileUploader.java
  src/main/java/com/api/TaveShot/global/config/SwaggerConfig.java
  src/main/java/com/api/TaveShot/global/constant/ApiConstant.java
  src/main/java/com/api/TaveShot/global/exception/ErrorType.java
  src/main/java/com/api/TaveShot/global/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/api/TaveShot/global/util/RedisUtil.java
  src/main/java/com/api/TaveShot/global/util/TimeUtil.java
Labels: :sparkles: Feature, 임준형, :twisted_rightwards_arrows: PullRequest

#21 fix solvedapi githubapi exception handling
  src/main/java/com/api/TaveShot/domain/authorization/service/AuthorizationService.java
  src/main/java/com/api/TaveShot/domain/authorization/service/GitHubApiService.java
  src/main/java/com/api/TaveShot/domain/authorization/service/SolvedAcApiService.java
  src/main/java/com/api/TaveShot/global/exception/ErrorType.java
Labels: :bug: BugFix, 임준형, :twisted_rightwards_arrows: PullRequest

#23 Breaking change login 수정
  src/main/java/com/api/TaveShot/domain/Member/domain/Member.java
  src/main/java/com/api/TaveShot/domain/post/post/controller/PostApiController.java
  src/main/java/com/api/TaveShot/domain/post/post/domain/Post.java
  src/main/java/com/api/TaveShot/global/constant/OauthConstant.java
  src/main/java/com/api/TaveShot/global/security/jwt/JwtProvider.java
  src/main/java/com/api/TaveShot/global/security/oauth2/CustomOAuthSuccessHandler.java
  src/main/java/com/api/TaveShot/global/util/SecurityUtil.java
Labels: :ambulance: BREAKING CHANGE, 임준형, :twisted_rightwards_arrows: PullRequest

#16 feat 티어별 커뮤니티
  src/main/java/com/api/TaveShot/domain/comment/controller/CommentApiController.java
  src/main/java/com/api/TaveShot/domain/comment/converter/CommentConverter.java
  src/main/java/com/api/TaveShot/domain/comment/domain/Comment.java
  src/main/java/com/api/TaveShot/domain/comment/dto/request/CommentEditRequest.java
  src/main/java/com/api/TaveShot/domain/comment/dto/response/CommentListResponse.java
  src/main/java/com/api/TaveShot/domain/comment/dto/response/CommentResponse.java
  src/main/java/com/api/TaveShot/domain/comment/editor/CommentEditor.java
  src/main/java/com/api/TaveShot/domain/comment/repository/CommentRepository.java
  src/main/java/com/api/TaveShot/domain/comment/repository/CommentRepositoryCustom.java
  src/main/java/com/api/TaveShot/domain/comment/repository/CommentRepositoryImpl.java
  src/main/java/com/api/TaveShot/domain/comment/service/CommentService.java
  src/main/java/com/api/TaveShot/domain/post/post/controller/PostApiController.java
  src/main/java/com/api/TaveShot/global/exception/ErrorType.java
Labels: :sparkles: Feature, 임준형, 박현빈, :twisted_rightwards_arrows: PullRequest
