Repository Tave100Shot/Server, pull requests merged in 2024-01, with the labels that each got.

#30 29 breaking change token response header에서 parameter로 변경
  build.gradle
  src/main/java/com/api/TaveShot/domain/comment/domain/Comment.java
  src/main/java/com/api/TaveShot/global/security/oauth2/CustomOAuthSuccessHandler.java
Labels: :ambulance: BREAKING CHANGE, 임준형

#31 refactor: 해답 블로그 response 데이터 추가
  src/main/java/com/api/TaveShot/domain/search/dto/GoogleItemDto.java
  src/main/java/com/api/TaveShot/domain/search/service/SearchService.java
Labels: :recycle: Refactor, 박정곤

#33 fix post merge
  src/main/java/com/api/TaveShot/domain/post/post/controller/PostApiController.java
  src/main/java/com/api/TaveShot/domain/post/post/converter/PostConverter.java
  src/main/java/com/api/TaveShot/domain/post/post/dto/request/PostCreateRequest.java
  src/main/java/com/api/TaveShot/domain/post/post/dto/response/PostResponse.java
  src/main/java/com/api/TaveShot/domain/post/post/repository/PostRepository.java
  src/main/java/com/api/TaveShot/domain/post/post/repository/PostRepositoryImpl.java
  src/main/java/com/api/TaveShot/global/config/S3FileUploader.java
  src/main/java/com/api/TaveShot/global/constant/OauthConstant.java
  src/main/java/com/api/TaveShot/global/exception/ErrorType.java
Labels: :bug: BugFix, 임준형

#39 fix 프론트 연동 오류 수정
  build.gradle
  exdata-png/blue_square.png
  exdata-png/green_square.png
  src/main/java/com/api/TaveShot/domain/Member/repository/MemberRepository.java
  src/main/java/com/api/TaveShot/domain/authorization/dto/SolvedUserInfo.java
  src/main/java/com/api/TaveShot/domain/authorization/service/AuthorizationService.java
  src/main/java/com/api/TaveShot/domain/authorization/service/SolvedAcApiService.java
  src/main/java/com/api/TaveShot/domain/base/BaseEntityConfig.java
  src/main/java/com/api/TaveShot/domain/comment/dto/response/CommentListResponse.java
  src/main/java/com/api/TaveShot/domain/comment/dto/response/CommentResponse.java
  src/main/java/com/api/TaveShot/domain/comment/repository/CommentRepositoryCustom.java
  src/main/java/com/api/TaveShot/domain/comment/repository/CommentRepositoryImpl.java
  src/main/java/com/api/TaveShot/domain/post/comment/controller/CommentApiController.java
  src/main/java/com/api/TaveShot/domain/post/comment/converter/CommentConverter.java
  src/main/java/com/api/TaveShot/domain/post/comment/domain/Comment.java
  src/main/java/com/api/TaveShot/domain/post/comment/dto/request/CommentCreateRequest.java
  src/main/java/com/api/TaveShot/domain/post/comment/dto/request/CommentEditRequest.java
  src/main/java/com/api/TaveShot/domain/post/comment/dto/response/CommentListResponse.java
  src/main/java/com/api/TaveShot/domain/post/comment/dto/response/CommentResponse.java
  src/main/java/com/api/TaveShot/domain/post/comment/editor/CommentEditor.java
  src/main/java/com/api/TaveShot/domain/post/comment/repository/CommentRepository.java
  src/main/java/com/api/TaveShot/domain/post/comment/repository/CommentRepositoryCustom.java
  src/main/java/com/api/TaveShot/domain/post/comment/repository/CommentRepositoryImpl.java
  src/main/java/com/api/TaveShot/domain/post/comment/service/CommentService.java
  src/main/java/com/api/TaveShot/domain/post/post/PostValidator.java
  src/main/java/com/api/TaveShot/domain/post/post/controller/PostApiController.java
  src/main/java/com/api/TaveShot/domain/post/post/converter/PostConverter.java
  src/main/java/com/api/TaveShot/domain/post/post/domain/Post.java
  src/main/java/com/api/TaveShot/domain/post/post/domain/PostTier.java
  src/main/java/com/api/TaveShot/domain/post/post/dto/response/PostResponse.java
  src/main/java/com/api/TaveShot/domain/post/post/repository/PostRepository.java
  src/main/java/com/api/TaveShot/domain/post/post/service/PostService.java
  src/main/java/com/api/TaveShot/domain/post/view/domain/ViewHistory.java
  src/main/java/com/api/TaveShot/domain/post/view/repository/ViewHistoryRepository.java
  src/main/java/com/api/TaveShot/domain/post/view/service/ViewService.java
  src/main/java/com/api/TaveShot/global/config/SecurityConfig.java
  src/main/java/com/api/TaveShot/global/constant/ApiConstant.java
  src/main/java/com/api/TaveShot/global/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/api/TaveShot/global/security/jwt/JwtProvider.java
  src/main/java/com/api/TaveShot/global/security/oauth2/CustomOAuthSuccessHandler.java
  src/main/java/com/api/TaveShot/global/util/SecurityUtil.java
  src/test/java/com/api/TaveShot/domain/post/post/service/PostDataInit.java
Labels: :bug: BugFix, 임준형, :twisted_rightwards_arrows: PullRequest, :white_check_mark: Test

#41 fix 커뮤니티 3번째 버그 수정
  build.gradle
  src/main/java/com/api/TaveShot/domain/post/comment/service/CommentService.java
  src/main/java/com/api/TaveShot/domain/post/post/converter/PostConverter.java
  src/main/java/com/api/TaveShot/domain/post/post/domain/Post.java
  src/main/java/com/api/TaveShot/domain/post/post/dto/request/PostCreateRequest.java
  src/main/java/com/api/TaveShot/domain/post/post/dto/response/PostResponse.java
  src/main/java/com/api/TaveShot/domain/post/post/repository/PostRepository.java
  src/main/java/com/api/TaveShot/domain/post/post/repository/PostRepositoryCustom.java
  src/main/java/com/api/TaveShot/domain/post/post/repository/PostRepositoryImpl.java
  src/main/java/com/api/TaveShot/domain/post/post/service/PostService.java
  src/main/java/com/api/TaveShot/domain/post/view/service/ViewService.java
  src/test/java/com/api/TaveShot/domain/post/post/service/PostDataInit.java
Labels: :bug: BugFix, 임준형

#42 26 feat 사용자에게 맞는 알고리즘 문제 추천
  build.gradle
  src/main/java/com/api/TaveShot/domain/recommend/controller/RecommendController.java
  src/main/java/com/api/TaveShot/domain/recommend/dto/RecProResponseDto.java
  src/main/java/com/api/TaveShot/domain/recommend/dto/UserCrawlingDto.java
  src/main/java/com/api/TaveShot/domain/recommend/service/CrawlingService.java
  src/main/java/com/api/TaveShot/domain/recommend/service/RecommendService.java
Labels: :sparkles: Feature, 박정곤

#45 fix: 멤버 정보 가져오는 코드 수정
  src/main/java/com/api/TaveShot/domain/recommend/controller/RecommendController.java
  src/main/java/com/api/TaveShot/domain/recommend/domain/TierCount.java
  src/main/java/com/api/TaveShot/domain/recommend/dto/RecResponseDto.java
  src/main/java/com/api/TaveShot/domain/recommend/repository/TierCountRepository.java
  src/main/java/com/api/TaveShot/domain/recommend/service/RecommendService.java
  src/main/java/com/api/TaveShot/domain/search/controller/SearchController.java
  src/test/java/com/api/TaveShot/domain/tierCount/TierCountTest.java
Labels: :bug: BugFix, :sparkles: Feature, :recycle: Refactor, 박정곤, :twisted_rightwards_arrows: PullRequest

#48 Cicd aws ecs cicd + docker
  .github/workflow/develop-ecs.yml
  .gitignore
  Dockerfile
  aws/task_definition.json
  build.gradle
  src/main/java/com/api/TaveShot/domain/authorization/controller/AuthorizationController.java
  src/main/java/com/api/TaveShot/global/config/SecurityConfig.java
  src/main/java/com/api/TaveShot/global/constant/OauthConstant.java
  src/main/java/com/api/TaveShot/global/health/HealthCheckController.java
  src/main/resources/application.yml
  src/test/java/com/api/TaveShot/domain/post/post/service/PostDataInit.java
Labels: 임준형, :twisted_rightwards_arrows: PullRequest, :construction_worker: CI/CD

#49 feat 게시판 단건 조회 및 댓글 작성자 프로필 이미지 추가
  build.gradle
  src/main/java/com/api/TaveShot/domain/post/comment/converter/CommentConverter.java
  src/main/java/com/api/TaveShot/domain/post/comment/dto/request/CommentEditRequest.java
  src/main/java/com/api/TaveShot/domain/post/comment/dto/response/CommentResponse.java
  src/main/java/com/api/TaveShot/domain/post/comment/repository/CommentRepositoryImpl.java
  src/main/java/com/api/TaveShot/domain/post/post/converter/PostConverter.java
  src/main/java/com/api/TaveShot/domain/post/post/dto/response/PostResponse.java
  src/main/java/com/api/TaveShot/domain/post/post/repository/PostRepositoryImpl.java
  src/main/java/com/api/TaveShot/global/constant/OauthConstant.java
  src/main/java/com/api/TaveShot/global/exception/ErrorType.java
  src/main/java/com/api/TaveShot/global/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/api/TaveShot/global/security/oauth2/CustomAuthFailureHandler.java
Labels: :bug: BugFix, :twisted_rightwards_arrows: PullRequest

#51 fix: workflow -> workflows rename
  .github/workflows/develop-ecs.yml
Labels: 임준형, :twisted_rightwards_arrows: PullRequest, :construction_worker: CI/CD

#53 46 feat 추천 문제 정보 추가하여 반환
  src/main/java/com/api/TaveShot/domain/recommend/controller/RecommendController.java
  src/main/java/com/api/TaveShot/domain/recommend/converter/StringListConverter.java
  src/main/java/com/api/TaveShot/domain/recommend/domain/ProblemElement.java
  src/main/java/com/api/TaveShot/domain/recommend/dto/RecProDetailResponseDto.java
  src/main/java/com/api/TaveShot/domain/recommend/dto/RecProRequestDto.java
  src/main/java/com/api/TaveShot/domain/recommend/dto/RecResponseDto.java
  src/main/java/com/api/TaveShot/domain/recommend/dto/UserCrawlingDto.java
  src/main/java/com/api/TaveShot/domain/recommend/repository/ProblemElementRepository.java
  src/main/java/com/api/TaveShot/domain/recommend/service/RecommendService.java
  src/main/java/com/api/TaveShot/domain/search/controller/SearchController.java
Labels: :sparkles: Feature, :recycle: Refactor, 박정곤

#56 ci/cd: main, develop 분리
  .github/workflows/develop-ecs.yml
  src/main/resources/application.yml
Labels: :wrench: Setting, 임준형, :twisted_rightwards_arrows: PullRequest, :construction_worker: CI/CD

#52 feat 컴파일러
  build.gradle
  src/main/java/com/api/TaveShot/domain/compiler/controller/CompilerController.java
  src/main/java/com/api/TaveShot/domain/compiler/converter/ProblemConverter.java
  src/main/java/com/api/TaveShot/domain/compiler/domain/BojProblem.java
  src/main/java/com/api/TaveShot/domain/compiler/dto/ProblemDto.java
  src/main/java/com/api/TaveShot/domain/compiler/dto/SubmissionRequestDto.java
  src/main/java/com/api/TaveShot/domain/compiler/repository/ProblemRepository.java
  src/main/java/com/api/TaveShot/domain/compiler/service/CompilerService.java
  src/main/java/com/api/TaveShot/domain/compiler/service/ProblemService.java
  src/main/java/com/api/TaveShot/global/exception/ErrorType.java
Labels: :bug: BugFix, 박현빈, :twisted_rightwards_arrows: PullRequest

#58 fix 존재하지 않는 번호에 대한 예외처리
  src/main/java/com/api/TaveShot/domain/recommend/repository/ProblemElementRepository.java
  src/main/java/com/api/TaveShot/domain/recommend/service/CrawlingService.java
  src/main/java/com/api/TaveShot/domain/recommend/service/RecommendService.java
  src/main/java/com/api/TaveShot/domain/search/service/SearchService.java
  src/main/java/com/api/TaveShot/global/exception/ErrorType.java
  src/main/resources/application.yml
Labels: :bug: BugFix, 박정곤

#59 fix develop to main 존재하지 않는 번호에 대한 예외처리
  .github/workflows/develop-ecs.yml
  build.gradle
  src/main/java/com/api/TaveShot/domain/compiler/controller/CompilerController.java
  src/main/java/com/api/TaveShot/domain/compiler/converter/ProblemConverter.java
  src/main/java/com/api/TaveShot/domain/compiler/domain/BojProblem.java
  src/main/java/com/api/TaveShot/domain/compiler/dto/ProblemDto.java
  src/main/java/com/api/TaveShot/domain/compiler/dto/SubmissionRequestDto.java
  src/main/java/com/api/TaveShot/domain/compiler/repository/ProblemRepository.java
  src/main/java/com/api/TaveShot/domain/compiler/service/CompilerService.java
  src/main/java/com/api/TaveShot/domain/compiler/service/ProblemService.java
  src/main/java/com/api/TaveShot/domain/recommend/repository/ProblemElementRepository.java
  src/main/java/com/api/TaveShot/domain/recommend/service/CrawlingService.java
  src/main/java/com/api/TaveShot/domain/recommend/service/RecommendService.java
  src/main/java/com/api/TaveShot/domain/search/service/SearchService.java
  src/main/java/com/api/TaveShot/global/exception/ErrorType.java
Labels: :bug: BugFix, 박정곤, :twisted_rightwards_arrows: PullRequest

#62 57 fix 존재하지 않는 번호에 대한 예외처리
  src/main/java/com/api/TaveShot/domain/recommend/service/CrawlingService.java
  src/main/java/com/api/TaveShot/domain/recommend/service/RecommendService.java
  src/main/java/com/api/TaveShot/domain/search/dto/GoogleItemDto.java
  src/main/java/com/api/TaveShot/domain/search/service/SearchService.java
  src/main/java/com/api/TaveShot/global/exception/ErrorType.java
Labels: :bug: BugFix, 박정곤

#65 fix: response 값 수정
  src/main/java/com/api/TaveShot/domain/compiler/service/ProblemService.java
  src/main/java/com/api/TaveShot/domain/search/dto/GoogleItemDto.java
  src/main/java/com/api/TaveShot/domain/search/service/SearchService.java
Labels: :bug: BugFix, 박정곤

#68 fix: metatags NPE 수정 (#67)
  src/main/java/com/api/TaveShot/domain/search/dto/GoogleItemDto.java
  src/main/java/com/api/TaveShot/domain/search/service/SearchService.java
Labels: :ambulance: BREAKING CHANGE, 임준형

#69 fix metatags null일때 npe로 인해 로그인창으로 이동되는 버그 수정
  src/main/java/com/api/TaveShot/domain/search/service/SearchService.java
Labels: :ambulance: BREAKING CHANGE, 임준형

#72 fix 문제 추천 및 문제 검색 숫자 integer 넘어가는 값 예외처리 및 integer에서 long으로 필드값 변경
  src/main/java/com/api/TaveShot/domain/recommend/controller/RecommendController.java
  src/main/java/com/api/TaveShot/domain/recommend/service/RecommendService.java
  src/main/java/com/api/TaveShot/domain/search/service/SearchService.java
  src/main/java/com/api/TaveShot/global/util/NumberValidator.java
Labels: :ambulance: BREAKING CHANGE, :bug: BugFix, 임준형, :twisted_rightwards_arrows: PullRequest

#73 docs: update Readme - Backend Architecture
  README.md
Labels: :memo: Docs, :twisted_rightwards_arrows: PullRequest

#74 docs: update Readme - Backend Architecture
  README.md
Labels: :memo: Docs, :twisted_rightwards_arrows: PullRequest
