Repository Tave100Shot/Server, pull requests merged in 2024-03, with the labels that each got.

#79 feat loginresponse 2차 인증 여부값 추가
  README.md
  src/main/java/com/api/TaveShot/domain/Member/dto/response/AuthResponse.java
  src/main/java/com/api/TaveShot/domain/Member/repository/MemberRepository.java
  src/main/java/com/api/TaveShot/domain/compiler/domain/BojProblem.java
  src/main/java/com/api/TaveShot/domain/recommend/controller/RecommendController.java
  src/main/java/com/api/TaveShot/domain/recommend/dto/RecProRequestDto.java
  src/main/java/com/api/TaveShot/domain/recommend/repository/ProblemElementRepository.java
  src/main/java/com/api/TaveShot/domain/recommend/service/RecommendService.java
  src/main/java/com/api/TaveShot/domain/search/dto/GoogleItemDto.java
  src/main/java/com/api/TaveShot/domain/search/service/SearchService.java
  src/main/java/com/api/TaveShot/global/security/oauth2/CustomOAuthSuccessHandler.java
  src/main/java/com/api/TaveShot/global/util/NumberValidator.java
Labels: :sparkles: Feature, 임준형

#81 fix: 누락 url securityconfig, jwtfilter에 추가 (#80)
  src/main/java/com/api/TaveShot/global/config/SecurityConfig.java
  src/main/java/com/api/TaveShot/global/security/jwt/JwtAuthenticationFilter.java
Labels: :bug: BugFix, 임준형

#82 feat: solution 작동 원리 변경
  src/main/java/com/api/TaveShot/domain/search/controller/SearchController.java
  src/main/java/com/api/TaveShot/domain/search/dto/GoogleItemDtos.java
  src/main/java/com/api/TaveShot/domain/search/service/SearchService.java
  src/main/java/com/api/TaveShot/global/exception/ErrorType.java
Labels: :bug: BugFix, :recycle: Refactor, 박정곤, :twisted_rightwards_arrows: PullRequest

#84 fix: 솔루션 제공 개수 변경
  src/main/java/com/api/TaveShot/domain/search/service/SearchService.java
Labels: :ambulance: BREAKING CHANGE, :bug: BugFix, 박정곤
